image: node:11-alpine

cache:
  paths:
    - node_modules/

stages:
  - lint
  - build
#  - test
  - production
  - deploy

lint:
  stage: lint
  script:
    - npm install
    - npm run lint

build:
  stage: build
  script:
    - npm install
    - npm run build

# test:
#  stage: test
#  script:
#    - apk add --no-cache chromium
#    - export CHROME_BIN=/usr/bin/chromium-browser
#    - npm install
#    - npm run test:ci
#  artifacts:
#    paths:
#      - coverage/
#    expire_in: 4 week

production:
  stage: production
  script:
    - npm install
    - npm run build:prod
  artifacts:
    paths:
      - dist/
    expire_in: 4 week
  only:
    - master
    - develop

deploy:
  stage: deploy
  script:
    - apk add  --no-cache curl
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -o $CF_ORG_NAME -s $CF_SPACE_NAME -u $CF_USERNAME -p $CF_PASSWORD -a api.sys.poc-pas.jikiai.net --skip-ssl-validation
    - ./cf push -f manifest.yml
  only:
    - develop

# deploy-coverage:
#  stage: deploy
#  script:
#    - apk add  --no-cache curl
#    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
#    - ./cf login -o $CF_ORG_NAME -s $CF_SPACE_NAME -u $CF_USERNAME -p $CF_PASSWORD -a api.sys.poc-pas.jikiai.net --skip-ssl-validation
#    - ./cf push -f manifest-coverage.yml
#  only:
#    - develop
